---
name: Update Browserslist database

on:
  schedule:
    # At 02:00 on day-of-month 1 and 15.
    - cron: '0 2 1,15 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  update-browserslist-database:
    name: Update Browserslist database
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push commits and create branches
      pull-requests: write # to comment on and label pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install and enable corepack
        shell: sh
        run: npm install -g corepack@latest --force && corepack enable

      - name: Configure git
        run: |
          git config user.name "fiximus"
          git config user.email "189535814+fiximus@users.noreply.github.com"

      - name: Update Browserslist database and create PR if applies
        uses: c2corg/browserslist-update-action@a76abb476199caea5399f9e28ff3f16e491ec566 # v2.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ vars.BROWSERSLIST_UPDATE_BRANCH || 'browserslist-update' }}
          base_branch: ${{ vars.DEFAULT_BRANCH || 'main' }}
          commit_message: 'chore(deps): update browserslist database'
          title: 'chore(deps): update browserslist database'
          body: Auto-generated by [browserslist-update-action](https://github.com/c2corg/browserslist-update-action/)
          labels: 'maintenance'
